from typing import Any
def estimate_tokens(text: str) -> int: ...
def config_hash(config: dict[str, Any]) -> str: ...
def content_hash(content: str, headings: list[dict[str, Any]], block_ids: list[str], schema: int) -> str: ...
def build_chunks(blocks: list[dict[str, Any]], config: dict[str, Any]) -> dict[str, Any]: ...
