from typing import Any
def normalize_text(value: str) -> tuple[str, int]: ...
def pdf_version() -> str: ...
def docx_version() -> str: ...
def extract_pdf(payload: bytes) -> dict[str, Any]: ...
def extract_docx(payload: bytes) -> dict[str, Any]: ...
